name: CI (Build and Lint)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: npm i
    
    - name: Type-check
      run: npm run typecheck
    
    - name: Lint
      run: npm run lint