name: Trigger Product Quantity Update on CRON Schedule

on:
  schedule:
    # - cron: "0 12 * * 1"
    - cron: "15 0 * * *"
  
  jobs:
    build:
      name: Product Quantity Update
      runs-on: ubuntu-latest
      steps:
        - name: cURL Request
          run: curl -X POST -d {} secrets.WEBHOOK_ENDPOINT